### ISSUE TITLE
[FEATURE REQUEST] Disable automatic updates for local apps and system components

### ISSUE THREAD

**Issue by R4ygen** [marticliment/WingetUI#1066]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

WingetUI, every now and then, tries to update system / windows related components.

Like: _.NET, C++, Vcredist, various KB123456, etc..._
And various system apps, like: _Edge, Xbox, Windows security, etc..._

All stuff that usually get updated via Windows Update anyway.

## Describe the solution you'd like

An option in the settings, to ignore all the updates of system components automatically. And leave them to Windows Update.

**OR** (even better probably)

An option in the settings, to ignore all updates for apps and programs that were not directly installed via WingetUI.
So, all the packages in the "Installed packages" tab wich are tagged as "Local PC" and "Microsoft store" as the source. (since as the time of writing this issue WingetUI does not support the MS store as a source, but it could change in the future)

**Comment by marticliment** [comment]
For what you are proposing, the best thing you could do would be ignoring the packages you don't want WingetUI to update; since there's no way to determine whether a package is a system component or not. Furthermore, Detecting which packages were installed through WingetUI and which not would need an important code rebase, and wouldn't be backwards compatible.

> since as the time of writing this issue WingetUI does not support the MS store as a source, but it could change in the future

The latest beta actually does support ms store

**Comment by R4ygen** [comment]
Oh yeah, my actual wrokaround is just to ignore them manually in fact, it's not a major issue, just an inconvenience.
I thought since many system utilities, like the Nirsoft's ones, have the option to "show/hide Windows programs from the list" thing, it would have been a simple thing to implement.

> The latest beta actually does support ms store
That's nice to hear!

**Comment by ppvnf** [comment]
> Oh yeah, my actual wrokaround is just to ignore them manually in fact, it's not a major issue, just an inconvenience.
> I thought since many system utilities, like the Nirsoft's ones, have the option to "show/hide Windows programs from the list" thing, it would have been a simple thing to implement.

A simple way to achieve that would be simply typing Microsoft on the search bar and then blacklist the packages that appear. 
 I could see being annoying to manually right click each package. Maybe the uninstall section could have a button to blacklist multiple packages like the update section?

another thing, @marticliment in the latest beta, is it possible to update MS Packages through WingetUI? because there is no way to blacklist them.

Now that I think about it, a problem with adding a button like I proposed is that there would need to have some check to see if the package is not local pc.

**Comment by marticliment** [comment]
> MS Packages

No. The only Microsoft Store upgradable packages will be listed as `Winget: msstore`, and are not the UWP applications, but rather the Win32 apps available through the store. This is how Winget works.

**Comment by marticliment** [comment]
This issue had no pending code fix
