### ISSUE TITLE
[Bug] Text Cursor not visible in any of the search fields

### ISSUE THREAD

**Issue by rp1231** [marticliment/WingetUI#115]
![WingetUI_8eXr7V2Q1R](https://user-images.githubusercontent.com/47380919/188518239-d5d08def-3926-4e20-90d0-2e2f1e5531de.png)
 
The text cursor is not visible in any of the search fields.

**Comment by martinet101** [comment]
Honestly, i found no way to change the cursor color. I'll will continue searching, though

**Comment by martinet101** [comment]
Yes, i kno what you mean, but it looks like in Qt there's no way to change it. I'll have to study this deeper

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/188585742-3caaba2f-c6bf-41c2-9458-1479cdcf0db4.png)
Look carefully. It is there, but it is white

**Comment by martinet101** [comment]
I'm sorry, i couldn't find a way to fix this.

**Comment by marticliment** [comment]
The issue is that Qt autogenerates the  color of it, and does not give any way to cusomize it

**Comment by marticliment** [comment]
Hello,

Custom Delegates are not supported on QLineEdit (non-qml UIs).

I'm sorry.

**Comment by PinkSerenity** [comment]
The cursor (caret) color is automatically generated by inverting the background color of the text field. It gets confused if the color isn't explicitly set though, that's why it's white here. I fixed it on my end by changing a line (803) in SpecificWidgets.py to:
`self.query.setStyleSheet("margin-top: 0px;border-top-right-radius:0px;border-bottom-right-radius:0px; background-color: #f2f8fb;")`

I was about to create a pull request for this when I realized that this would mess with the dark theme. Since I'm not really experienced with Qt (I have actually never worked with it) I decided to just comment here. Somehow the solution will require changing the stylesheet of `query` when a different theme is selected. I'm sorry that I wasn't able to help further.
