### ISSUE TITLE
[BUG] listing packages on empty query is no longer working

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1365]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I don't really use this option, I was just testing something else, so I don't mind if it would be removed. 
<img width="374" alt="Screenshot 2023-09-17 210932" src="https://github.com/marticliment/WingetUI/assets/73800734/b531dc83-02c8-44b8-8bf3-dcc7f825c643">
After activating it I noticed that only a few hundred chocolatey packages were listed and that winget packages were duplicated

### WingetUI Log

```text
na
```

### Package Managers Logs

```text
na
```

**Comment by marticliment** [comment]
This feature is likely to be removed. Chocolatey has deprecated all-package listing, and other package managers that are going to be added don't support this feature either (dotnet tool, nuget, etc.), and the operation of loading and processing so much packages is very resource-intensive. 

For the moment, all package managers have been migrated from the PackageManager to the DynamicPackageManager class, enabling dynamic queries and removing all-listing support. While all-listing enabled faster searching, the resource usage when caching packages was notorious. Furthermore, packages wouldn't get updated regularly.

Moreover, I have in mind some kind of _Welcome_ interface, showing some recommended packages  and other useful shortcuts, an idea similar to the one behind the new Settings App homepage on Windows 11.

What do you think about this? Should I re-add all-listing packages for winget and scoop?

**Comment by ppvnf** [comment]
> Moreover, I have in mind some kind of Welcome interface, showing some recommended packages and other useful shortcuts, an idea similar to the one behind the new Settings App homepage on Windows 11.

I think that would be pretty cool, specially if most of the packages were open source, however I am not sure how a recommended package list could be objectively made since analytics across package managers are not always good (I think only Chocolatey provides download counter). Maybe a quizz for the users, but this sounds too much hassle. 

> Should I re-add all-listing packages for winget and scoop?

I wouldn't mind if the option was removed entirely, but there was an issue where people asked for this, so maybe this should also be asked there (https://github.com/marticliment/WingetUI/issues/1062).

**Comment by ppvnf** [comment]
about the recommended package list, do you have any idea how to make it? I do not. maybe create a discussion so people can suggest sources for it

**Comment by ppvnf** [comment]
> I thought of using winget.run's or winstall.app APIs to get recommended packages

I guess that would be fine

**Comment by JAK1047** [comment]
Just a note on that idea you had that I figured I'd leave since I went down the exact same path of trying to pull a popular app list previously (part of an SCCM request page I created for a company a few months back). 

Chocolatey has no telemetry tracking it:
https://docs.chocolatey.org/en-us/information/security
"No Data Collection / Telemetry - No call home, not even in our commercial options (license tracking is honor-based) and there are organizations (or internal processes) that verify/validate (and karma) that will adjust any abuses of licensing."

Winget uses the Microsoft Windows Privacy Policy and while it does log installs (seen here on in the source code https://github.com/microsoft/winget-cli/blob/master/src/AppInstallerCommonCore/AppInstallerTelemetry.cpp) when they had a discussion on making this telemetry data transparent the consensus was it would need to be discussed further. https://github.com/microsoft/winget-pkgs/discussions/39736#discussioncomment-5233369

NPM DOES track it: 
https://docs.npmjs.com/policies/privacy
But I was never able to find any API publicly accessible to access the data. Same for Nuget outside of scraping this page with web calls:
https://www.nuget.org/stats

Scoop has a PR to add telemetry in: 
https://github.com/ScoopInstaller/Scoop/pull/5249
But near as I can tell nothing else was done with it afterwards.

Winstall had a popular app json in the GitHub, but it hadn't been touched in 3 years and I wasn't aware Winget.run's had one. I actually eventually just hit the popular app list for flatpack myself:
[https://flathub.org/api/v1/apps/collection/popular](https://flathub.org/api/v1/apps/collection/popular)
Since it was available in JSON with links to the icons already, a summary property, and there was no auth or setup needed. Mind you it's for Linux, but I just compared the names to a list of available software I had and everywhere there was a match I knew I could offer it. Came out to about what I expected: Chrome, Firefox, Edge, VLC, VS Code, Discord, etc. So, I was happy with it.
