### ISSUE TITLE
[ENHANCEMENT] use msstore icon in the discovery section

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1372]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

I think in this case it is better to use MSStore icon instead of Winget for source:
![Screenshot 2023-09-19 092420](https://github.com/marticliment/WingetUI/assets/73800734/1e178a57-1ed6-45b0-8307-a5de6bba1ff4)

### Describe how this improvement could help users.

make clearer that the package is not a regular winget one

**Comment by marticliment** [comment]
I wouldn't do that, since the install process is handled by Winget.

There are two types of Microsoft Store packages:
1. The ones installed and updated by winget, identified as winget: msstore (they are part of winget)
2. The ones managed by the Microsoft Store directly, that are not updated and cannot be installed from Winget (shown as Microsoft Store packages)

I think this difference should remain marked, and the Winget: msstore packages should remain using the Winget icon

**Comment by ppvnf** [comment]
that makes sense, I just tested it
