### ISSUE TITLE
[ENHANCEMENT] (Close running application before upgrade, and start after finicsh installation)

### ISSUE THREAD

**Issue by killo3967** [marticliment/WingetUI#1800]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

I have installed CrystalDiskInfo that is always running, because it's a hdd monitor, and when i update this program, the installation said that i have the process running and ask me to close it. After closing i manually push the "Contiue" buttom of the installer and finish the installation. And after all this i must start the program manually.

### Describe how this improvement could help users.

I think it could be a good option to have two check-boxes in the program configuration one for "Close the app before installation" and other to "Start the app after installation" .

**Comment by marticliment** [comment]
Hello,

Killing and relaunching the app is not handled by WingetUI, but rather by the installer of CrystalDisk. When ran in silent mode, it should not ask to quit the application (because then it is not silent.)

You should report this issue to CrystalDisk maintainers, and ultimately to Winget, one of the package managers used to install and updates from WingetUI. Please remember that WingetUI is only the interface.

Hope this helps!
