### ISSUE TITLE
[BUG] Malicious behavior detection in CrowdStrike Falcon

### ISSUE THREAD

**Issue by DeusMaximus** [marticliment/WingetUI#1927]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

After the latest 3.0 update, CrowdStrike Falcon detects malicious activity when attempting to run WingetUI.

The tactic detected is: Defense Evasion via Reflective Code Loading

CrowdStrike Falcon describes this as:
A suspicious .NET module was loaded into the process. Adversaries may load malicious .NET assemblies into a process in order to conceal the execution of malicious payloads. Investigate the process and surrounding events.

### Steps to reproduce the issue

Allow autoupdate from 2.x to 3.0 on a system with CrowdStrike Falcon installed.

### WingetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

### Relevant information

Issue occurred directly after the 3.0 auto update.

### Screenshots and videos

![2024-03-14_08h07_11](https://github.com/marticliment/WingetUI/assets/10080364/e25918c8-a1c6-4876-8889-8f3f5c79e687)

**Comment by marticliment** [comment]
Yes, definitely a false-positive

**Comment by daskydasky** [comment]
Similar issue here with CrowdStrike. Previous version worked okay, but the update to v3.0.0 did not. It installs ok, but when launching WingetUI.exe it get killed by CS. 
Deatils about the detection:
Severity: High
Objective: Keep Access
Tactic & technique: Defense Evasion via Reflective Code Loading
Technique ID: T1620
IOA Name: SuspiciousDotNetAssemblyLoad
IOA Description: A suspicious .NET module was loaded into the process. Adversaries may load malicious .NET assemblies into a process in order to conceal the execution of malicious payloads. Investigate the process and surrounding events.
Command Line: "C:\Program Files\WingetUI\WingetUI.exe" --daemon

https://www.virustotal.com/gui/file/6cb0d0a2aa417c25a321b71eea761f918637806aa389566d6e4a8cd6185ca32c/detection
