### ISSUE TITLE
Feature: Installation source Steam

### ISSUE THREAD

**Issue by Sacred-Shadow** [marticliment/WingetUI#202]
Steam games are also recognized in the installed packages.
These things get "Steam" as the package ID.

In this case you can write "Steam" instead of "Local PC" for "Installation source".

**Comment by martinet101** [comment]
I get your point, but the "Installation source" is the method WingetUI uses to obtain/update/uninstall packages.

Since steam games are handled by steam and registered as unknown packages for winget nor scoop, the installation source is local (aka third-party to winget or scoop).

In other words, there is no WingetUI integration with steam, and the uninstall entries are the ones provided by Windows Registry (not by winget or scoop), thoug local pc

**Comment by ppvnf** [comment]
@marticliment Would you mind if I tried to implement a solution similar to https://github.com/marticliment/WingetUI/issues/502?

**Comment by marticliment** [comment]
If you want to try, go for it! If it works i'll definitely merge it
For the icons, if you want just put a placeholder and i'll get the steam icons from the icon database i use

**Comment by ppvnf** [comment]
Done. Now I just need to figure out how to use Github Desktop so I can upload it

**Comment by marticliment** [comment]
Thanks!
