### ISSUE TITLE
Feature: global/local option switch for winget and scoop separately

### ISSUE THREAD

**Issue by reaseno** [marticliment/WingetUI#206]
My system got messed up with WingetUI because I installed my applications globally with Admin. But if you want to use scoop with WingetUI, you are forced to work without admin. Or to always remember to manually switch back and forth.

This has now led me to the fact that updates can no longer be performed, or an update is always displayed again, although the update has already been performed successfully. This is because the app has now been installed locally in addition to the original global installation.

For me, it would be the best solution to have an option where you can say separately for winget and scoop, whether they should work globally or locally.

**Comment by martinet101** [comment]
I understand that you have been running WingetUI as admin, right?

**Comment by reaseno** [comment]
I tried not to use it as administrator, which didn't work for me. Too error-prone.

**Comment by martinet101** [comment]
I have found no ways to run a command from an elevated program as the standard-privileged user. (though i'm still studying how to do this)

As i understand, broken apps are only happening on scoop, right?

**Comment by reaseno** [comment]
Everything the other way around 😅

1. I currently use WingetUI as recommended as normal user.
2. I only have problems with winget programs, because I installed my programs before WingetUI as admin globally. Now with WingetUI as a normal user, updates are installed locally. So now programs are partially installed globally and locally.

**Comment by martinet101** [comment]
I suppose this is the same issue described in #142 then?

**Comment by reaseno** [comment]
Yes

**Comment by ppvnf** [comment]
I believe https://github.com/marticliment/WingetUI/issues/142 fixed the problem with Winget and https://github.com/marticliment/WingetUI/issues/81 solved the problem with Scoop (at least regarding updates).

**Comment by marticliment** [comment]
That feature, as I understood, asked for a toggle to swich between local and global installs, right?

**Comment by ppvnf** [comment]
I believe OP asked for a global/local switch because of being unable to update global apps (which was fixed for both Winget and Scoop).

Regarding the global/local switch feature request, there's also these issues about them:

Scoop: https://github.com/marticliment/WingetUI/issues/81
Winget: https://github.com/marticliment/WingetUI/issues/123

**Comment by marticliment** [comment]
This issue has been fixed, since:
1. WingetUI already detects the installation scope of packages before updating them (so no more broken updates). This also has been greaitly improved by winget-cli  since the time of opening of this issue.
2. When installing new apps, the user can choose the installation scope:
![image](https://user-images.githubusercontent.com/53119851/233400729-17743cd6-bab6-4ff7-a6b9-2e1d52c324e0.png)

**Comment by reaseno** [comment]
That's very nice. Thank you 👍
