### ISSUE TITLE
[BUG] Says "installed successfully" while winget says not

### ISSUE THREAD

**Issue by Kaligula0** [marticliment/WingetUI#2093]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I ran batch update. WingetUI tells that an app* installed succesfully, but after refresh the update is still available.
*) in my case it's EpicGames.EpicGamesLauncher, JRSoftware.InnoSetup, TheDocumentFoundation.LibreOffice.HelpPack, Microsoft.WindowsAppRuntime.1.5
CLI summary (for EpicGames.EpicGamesLauncher and TheDocumentFoundation.LibreOffice.HelpPack):
```
No applicable upgrade found.
A newer package version is available in a configured source, but it does not apply to your system or requirements.
```
The same is when invoking winget via CLI.

CLI summary (for JRSoftware.InnoSetup):
```
No available upgrade found.
No newer package versions are available from the configured sources.
```
The same is when invoking winget via CLI.

CLI summary (for Microsoft.WindowsAppRuntime.1.5) is different:
```
Found Windows App Runtime [Microsoft.WindowsAppRuntime.1.5] Version 1.5.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
/
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  0.00 B / 60.7 MB
████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  25.7 MB / 60.7 MB
██████████████████████████████  60.7 MB / 60.7 MB
Successfully verified installer hash
\
Successfully installed
```
When invoking winget via CLI it says `No installed package found matching input criteria.`.

### WingetUI Log

```text
For the sake of privacy it's pasted there → http://kaligula.uk/ctrlv/GitHub-WingetUI-Issue2093-WingetUIlog-1.txt
```

### Package Managers Logs

```text
For the sake of privacy it's pasted there → http://kaligula.uk/ctrlv/GitHub-WingetUI-Issue2093-PackageManagerslog-1.txt
```

**Comment by marticliment** [comment]
When a package is already upgraded, there is no point on throwing an error. The user desires to have the app updated, triggers the update but for whatever the reason (for example, an autoupdater on the app) the app is alreadu up-to-date. There is no point on annoying the user with an error which says `The app did not update because it already was up-to-date`, because the user intention has still been accomplished

**Comment by marticliment** [comment]
> CLI summary (for Microsoft.WindowsAppRuntime.1.5) is different:
> 
> ```
> Found Windows App Runtime [Microsoft.WindowsAppRuntime.1.5] Version 1.5.1
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> /
> ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  0.00 B / 60.7 MB
> ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  25.7 MB / 60.7 MB
> ██████████████████████████████  60.7 MB / 60.7 MB
> Successfully verified installer hash
> \
> Successfully installed
> ```
> 
> When invoking winget via CLI it says `No installed package found matching input criteria.`.

This is a specific issue with this package. See microsoft/winget-pkgs for more details

**Comment by Kaligula0** [comment]
> …because the user intention has still been accomplished, and no further action is required

Has not been accomplished, because those packages are not being updated. After updating "successfully" and refreshing the list, they come back again to the list (as not updated). And Windows's "Programs and Functions" still shows old version. (In fact, I saw 2 Inno Setup versions, old and new, but Epic and LibreOffice are listed only as old version).

**Comment by marticliment** [comment]
This is then another issue, caused by WinGet. WinGet sometimes fails to detect some packages or detects incorrect versions for them (most likely this is also the package maintainer's fault for not having the package expose the correct package details). Therefore, this issue cannot be fixed from WinGetUI.

**Comment by Kaligula0** [comment]
I think we still don't talk about the same issue. What I reported here is that package doesn't get updated (winget CLI tells `No applicable upgrade found.` or `No available upgrade found.`), but WingetUI shows that package was succesfully updated.

**Comment by marticliment** [comment]
There are two factors causing this bug:

1. WinGet detecting non-existing upgrades: It reports false upgrades and then, when attempting to install them, reports that they are already installer.
2. WingetUI (not WinGet) reporting success when an update happens to be already installed.

The first one is a bug with WinGet, which cannot be fixed from WinGetUI.
The second one is intentional design, since the first issue isn't supposed to happen. The design helps mitigate issues when an upddate has been installed externally and WinGetUI attempts to install it again

**Comment by iamLazyCode** [comment]
> This is then another issue, caused by WinGet. WinGet sometimes fails to detect some packages or detects incorrect versions for them (most likely this is also the package maintainer's fault for not having the package expose the correct package details). Therefore, this issue cannot be fixed from WinGetUI.

seeing same kind of issue with this app

![Image](https://github.com/user-attachments/assets/f3959a52-f4b3-4aab-8673-0fa177fada54)

**Comment by marticliment** [comment]
Here, WinGet is refusing to install the app due to incompatible system requirements. I can't help here, either contact winget or the package maintainer

**Comment by iamLazyCode** [comment]
> Here, WinGet is refusing to install the app due to incompatible system requirements. I can't help here, either contact winget or the package maintainer

running this manually did install it

```
winget install --id=TGRMNSoftware.BulkRenameUtility  -e
```

**Comment by mrixner** [comment]
I highly suspect why the command line worked is because you installed it fresh rather than upgrading it as UniGetUI is doing.

Irrespective, that mismatch is likely the fault of the package maintainer and UniGetUI can't really capitalize on that - unless Martí thinks it's a good idea to retry this specific failed upgrade with a followup install, but I think that's too niche and could cause problems if the installer isn't properly designed for that.

**Comment by iamLazyCode** [comment]
> I highly suspect why the command line worked is because you installed it fresh rather than upgrading it as UniGetUI is doing.
> 
> Irrespective, that mismatch is likely the fault of the package maintainer and UniGetUI can't really capitalize on that - unless Martí thinks it's a good idea to retry this specific failed upgrade with a followup install, but I think that's too niche and could cause problems if the installer isn't properly designed for that.

aah i guess next time il try upgrade my bad dint realise it was an clean install

**Comment by marticliment** [comment]
> I highly suspect why the command line worked is because you installed it fresh rather than upgrading it as UniGetUI is doing.
> Irrespective, that mismatch is likely the fault of the package maintainer and UniGetUI can't really capitalize on that - unless Martí thinks it's a good idea to retry this specific failed upgrade with a followup install, but I think that's too niche and could cause problems if the installer isn't properly designed for that.

Yep (to both)
