### ISSUE TITLE
[BUG] "Run cleanup and clear cache" doesn't clean Scoop's cache

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/WingetUI#2151]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

The Run button for "Run cleanup and clear cache" under Scoop in the Settings only removes old versions of installed Scoop apps. It does not clear/clean/remove the cached downloads, which it should.

### WingetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

**Comment by marticliment** [comment]
Please attach the contents of the file on `C:\Program Files\WingetUI\Assets\Utilities\scoop_cleanup.cmd`

**Comment by marticliment** [comment]
And running this script manually doesn't work either?

**Comment by marticliment** [comment]
What happens if you run the script on a non-admin command prompt?

**Comment by 265785** [comment]
The problem should because the `scoop` command is directed to the file `scoop.cmd`, which is also a batch file. Running it will replace and stop `scoop_cleanup.cmd`, the current batch file. We can use the command `call scoop` in `scoop_cleanup.cmd` to solve this problem, like the example below: 

```
(PUSHD "%~DP0")&(REG QUERY "HKU\S-1-5-19">NUL 2>&1)||(powershell -Command "Start-Process '%~sdpnx0' -Verb RunAs"&&EXIT)

@echo on
echo This script will clean the Scoop cache and run the cleanup command.
echo|set/p="Press <ENTER> to continue or CLOSE this window to abort this process"&runas/u: "">NUL
cls
echo Cleaning Scoop cache...
call scoop cleanup --all --global
@echo on
call scoop cache rm --all --global
@echo on
call scoop cleanup --all
@echo on
call scoop cache rm --all
@echo on
echo Done!
pause
```

Because `scoop.cmd` contains `@echo off` command, in order to echo all commands, `@echo on` is needed to add after each `call scoop` commands. If it is not needed, just delete them.

The first line of the program above: `(PUSHD "%~DP0")&(REG QUERY "HKU\S-1-5-19">NUL 2>&1)||(powershell -Command "Start-Process '%~sdpnx0' -Verb RunAs"&&EXIT)` , is to automatically get administrator access. If it is not needed, just delete it.

**Comment by marticliment** [comment]
I did not konw this behaviour, thanks for pointing it out!

**Comment by 265785** [comment]
I have already run the example on my PC, it is safe. If you care about the safety and administrator access, Only replace "`scoop`" as "`call scoop`" in `scoop_cleanup.cmd` is also enough.
```
@echo off
echo This script will clean the Scoop cache and run the cleanup command.
echo|set/p="Press <ENTER> to continue or CLOSE this window to abort this process"&runas/u: "">NUL
cls
echo Cleaning Scoop cache...
call scoop cleanup --all --global
call scoop cache rm --all --global
call scoop cleanup --all
call scoop cache rm --all
echo Done!
pause
```
