### ISSUE TITLE
[ENHANCEMENT] Allow ignoring winget packages with an unknown version

### ISSUE THREAD

**Issue by i0ntempest** [marticliment/WingetUI#2182]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

winget by default will not list packages with an unknown version as updateable. I think this project should add a toggle to allow this as well, and even enable it by default to be consistent with winget.

### Describe how this improvement could help users.

Decluttering update list.

**Comment by marticliment** [comment]
Packages with unknown versions will be handled manually by WingetUI, and when you upgrade them, they will not show again until a new version different from the already updated is available. Therefore, it does not make sense anymore to treat them differently. WingetUI used to have a toggle for this, but it was ultimately removed due to the implementation of this self-handling
