### ISSUE TITLE
advanced search

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#223]
![Captura de tela 2022-10-09 094756](https://user-images.githubusercontent.com/73800734/194775600-c3eb976f-3d37-4231-9655-e3a0c2f6a83e.png)

What about being able to click the + button (or something else) and have it display advanced search options like below:

![Captura de tela 2022-10-09 162002](https://user-images.githubusercontent.com/73800734/194775595-24a3c71c-3bc1-44f5-b15e-e6ee8d4f0647.png)

Also, while in Winget.run it's not possible, I think it would be nicer if you could click the options instead of having to type them.

Related:
https://github.com/martinet101/WingetUI/issues/219
https://github.com/martinet101/WingetUI/issues/189
https://github.com/martinet101/WingetUI/issues/209

**Edit: what about also being able to differentiate lower/upper case while searching**

**Comment by ppvnf** [comment]
I know filtering packages using tags is possible with `winget search --tag`. For publisher/description maybe search using the data already fetched by WingetUI

**Comment by Satanarious** [comment]
### Filtering by tag:

![image](https://user-images.githubusercontent.com/42642682/194778046-f8f29e47-5cd9-4479-9c65-c3f7aa407e13.png)

### Filtering by publisher (this is a workaround):

Because mostly developers name their package ids with their publisher names as prefixes. 
e.g. Adobe uses "Adobe." prefix, while Microsoft uses "Microsoft." prefix

![image](https://user-images.githubusercontent.com/42642682/194778312-70e54f8a-8601-4b1c-a1ee-ba60bc69d68d.png)

For cases where no packages are found for that id (assuming the above rule for id nomenclature), use the currently selected package's id's prefix. 
e.g.
Publisher name : Wildfire Games
Package id         : WildfireGames.0AD

Since publisher has a space in its name, so we search here by prefix of the package id.

![image](https://user-images.githubusercontent.com/42642682/194779553-18940d54-cc0e-4445-a745-fdcd9b1a4c44.png)


### Filtering by description:

I'm not sure about this one, would have to do some research regarding that

**Comment by ppvnf** [comment]
For description filtering (and maybe publisher filtering), would it be possible to fetch the manifests, for example https://github.com/microsoft/winget-pkgs/blob/master/manifests/y/YACReader/YACReader/9.9.1/YACReader.YACReader.locale.en-US.yaml, and then locate the publisher/description within? I suppose this is how Winget.run works

**Comment by martinet101** [comment]
In order to implement this, it would require to actually download all the mainfests and then manually load all data.

However, it is a thing i am studying to do, since it would mean lots of improvements in terms of search availability and filters.

**Comment by Satanarious** [comment]
winstall already maintains a json of all package, I've heard the developer of that website is going to open source that api. I suggest having a chat with that developer before investing in something like this. You would wanna look at #209 for more info.

**Comment by ppvnf** [comment]
I believe it's possible to open/display json files on PowerShell: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-7.3
I am not sure how this could be useful to implement in WingetUI though

**Comment by marticliment** [comment]
That's one of the issues that guinget has, its slow load times because of this parsing. 
I guess parsing wouldn't be the issue, but rather the fetching.

**Comment by ppvnf** [comment]
This feature also depends on https://github.com/marticliment/WingetUI/issues/712 I guess

**Comment by ppvnf** [comment]
what about also being able to differentiate lower/upper case while searching?

**Comment by marticliment** [comment]
I suppose so
