### ISSUE TITLE
[FEATURE REQUEST] Option to ignore current update

### ISSUE THREAD

**Issue by rp1231** [marticliment/WingetUI#418]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**

## Is your feature request related to a problem? Please describe.

Sometimes you want to ignore a certain update of an app as the update is buggy on your system.
In such a situation you only want to ignore the current update and not be notified of it again and again.
But you would want to be notified of future versions after this one.

## Describe the solution you'd like

An option to ignore the current update in the context menu would be great.
It would be an alternative to adding an app to the blacklist.
It would allow you to ignore the current update but still be notified of future updates.
<img width="827" alt="Screenshot 2022-11-15 082305" src="https://user-images.githubusercontent.com/47380919/201815750-4aca29ad-5bb0-4eb9-94ae-adacf45db838.png">

**Comment by martinet101** [comment]
Oh, I see

**Comment by Ch3ri0ur** [comment]
It might also be useful to suspend updates for a bit e.g.:

- Suspend updates for a certain time ( don't bother me for that package for a month)
- Suspend updates till the next minor/major version
- Maybe a combination 'next minor version + a month' to get fixes

**Comment by mischkl** [comment]
+1 from me, this is the one feature I'm missing. In my case, sometimes WinGet *thinks* there is an update even when the update has already been installed, due to a version mismatch between the database and the reported installed version. I've had this problem with the following packages:

chrisant996.Clink
Git.Git
Microsoft.OpenJDK.11
Microsoft.VCRedist.2013.x86
Microsoft.Teams
Microsoft.WindowsSDK

Ultimately I can't say for sure if this will always be a problem for all of these packages' updates into the future, so I'd ideally like to be able to ignore just the "current" update versions but still get notified when newer versions are available.

FWIW this is a feature I am familiar with from the (proprietary) Mac software MacUpdater, and always found quite useful.

**Comment by marticliment** [comment]
On the next WingetUI Release👀
![image](https://user-images.githubusercontent.com/53119851/233734954-0e6de67b-30de-4bf2-bb3d-ae74ff1da80f.png)
