### ISSUE TITLE
[FEATURE REQUEST] Change 'Blacklist apps' button text to 'Blacklist packages' (and maybe elsewhere) for consistency

### ISSUE THREAD

**Issue by elliot-100** [marticliment/WingetUI#573]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI (1.5.3)**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**

## Is your feature request related to a problem? Please describe.

As a new user, I found it somewhat confusing that there's a 'Blacklist apps' button, but 'packages' is used elsewhere, e.g. context menu for a single package. Initially I thought they referred to different kinds of install.

I have looked at the UI and I think all other uses of 'app'/'application' refer to WingetUI itself, except for _WingetUI settings -> Package manager preferences -> Scoop preferences -> Show Scoop **apps** as lowercase_ . Maybe that's appropriate Scoop terninology? But then a bit further down it says 'Uninstall Scoop (and its packages)'.

## Describe the solution you'd like

Button text reads 'Blacklist packages', and 'app/apps' isn't used to describe 'package/packages' anywhere else, unless there is a good reason.

**Comment by ppvnf** [comment]
I agree with you regarding changing "Show Scoop apps as lowercase" to "Show Scoop packages as lowercase".

I believe the reason to use "Blacklist apps" instead of "Blacklist packages" was that there used to be an extra button to update all packages, so that text needed to be smaller. But since that button was removed I agree with you that "Blacklist packages" makes more sense.
