### ISSUE TITLE
[BUG/ISSUE] Having a real Matrix moment here.. Something is up with this right?

### ISSUE THREAD

**Issue by Wateraga** [marticliment/WingetUI#652]
![image](https://user-images.githubusercontent.com/20799621/215241006-4bc40094-a1ab-4a47-a492-af3afa5b6866.png)

It reading, "Scoop Is Owned Everything Is Okay" as a sentence  is very disconcerting, would love an explanation or a bit of reassurance that my system isn't compromised. 

This is my Installed Packages page.

Happened after updating to latest edition with Chocolatey support. I had previously added all of the Scoop buckets and restarted my machine, after restarting, the buckets list was empty and upon trying to add them again it say it was added but it doesn't show in the list, the list stays blank.

[WingetUI_Log.txt](https://github.com/marticliment/WingetUI/files/10525263/WingetUI_Log.txt)

**Comment by marticliment** [comment]
don't worry, this is not a cirut or anything. some text was printed and it has been identified as packages, splitting it in the weird way.

could you please check if you have git installed in your system? (scoop requires it to run)

**Comment by marticliment** [comment]
Btw, do you have a custom system installation? What does the shovel mean?
![image](https://user-images.githubusercontent.com/53119851/215315548-73ed4589-9d90-4d9d-bf8f-3cb140c7bf1d.png)

**Comment by Shmeeg** [comment]
> don't worry, this is not a virus or anything. some text was printed and it has been identified as packages, splitting it in the weird way.
> 
> could you please check if you have git installed in your system? (scoop requires it to run)

I do have Git installed.
I was previously using Scoop standalone but had just uninstalled all scoop apps and then scoop itself, then installed Scoop through WingetUI to attempt to consolidate it all.



> Btw, do you have a custom system installation? What does the shovel mean? ![image](https://user-images.githubusercontent.com/53119851/215315548-73ed4589-9d90-4d9d-bf8f-3cb140c7bf1d.png)

Shovel is this "https://github.com/Ash258/Scoop-Core"
To be honest I installed it during the honeymoon phase of dsocovering Windows Package Managers and being like "wow Winget/Scoop/Chocolatey is amazing I'm gonna just install everything I see"
I don't fully understand what it does or if it's needed and would actually like a fresh start on the entire thing so will probably be doing that soon.

**Comment by Shmeeg** [comment]
> don't worry, this is not a virus or anything. some text was printed and it has been identified as packages, splitting it in the weird way.
> 
> could you please check if you have git installed in your system? (scoop requires it to run)
 
Is there any explanation for why them particular words appear and why they appear to for part of sentences, particlarly the "Scoop Is Owned", "But The Current" and "To Add An"?
Just strikes me as very strange.

**Comment by Shmeeg** [comment]
Reinstalled Scoop and the weird updates disappeared but the Buckets still won't show after installing, a fresh install of everything sounds like a good plan for today, clicking the install Scoop button opens a random folder (that iirc I set in some config file to be the default Winget installation folder for packages but it never worked and has always been empty.)

Do you know how I could set a default insatallation path for all packages on a different drive, any methot I have tried just hasn;t worked (eg, D:\Software\Apps).

Thank you for taking the time to respond mate I really appreciate it.

**Comment by marticliment** [comment]
they are just the first words of each line.

Yes, I would recommend you migrating to regular scoop, since I have no clue if scoop shovel is compatible

**Comment by Shmeeg** [comment]
> > Is there any explanation for why them particular words appear and why they appear to for part of sentences, particlarly the "Scoop Is Owned", "But The Current" and "To Add An"?
> 
> they are just the first words of each line.
> 
> Yes, I would recommend you migrating to regular scoop, since I have no clue if scoop shovel is compatible. From where did you install wingetui?

I believe it was from the releases page on this Repo.

Could you give me a brief rundown of what files/folders I should delete and powershell commands to run in order to start fresh?
Is it just a case of uninstalling Scoop, Chocolatey and then WingetUI and deleting the associated programdata folders?
Then reinstalling WingetUI and using that to install Scoop, then installing Chocolatey and selecting to integrate it in the WingetUI settings?
Also should I use the System Chocolatey? I don't know what difference it would make, WingetUI can't insatll Chocolatey by itself right? So by default it would use System Chocolatey ig.

Sorry for the questions but I am really enjoying WingetUI and would like a fresh install without the issues I have probably caused with running random commands and insatlling random bits of shite.

**Comment by marticliment** [comment]
you should delete:

- the folder where WingetUI is installed
- a folder called .wingetui placed on your user directory 
 - remove the folder caller scoop placed on your user directory (Warning, will delete also scoop apps) 
no need to remove anything else. 

Then, install wingetui and enable scoop, winget and chocolatey. scoop is then going to be installed. 

For winget and chocolatey, you don't need to do anything.

**Comment by nannerpusser** [comment]
> Do you know how I could set a default insatallation path for all packages on a different drive, any method I have tried just hasn;t worked (eg, D:\Software\Apps).
> 
> Thank you for taking the time to respond mate I really appreciate it.

I can (probably) answer that. It's permission-related and entirely a Windows and/or local installation issue. This is a very deep issue that has a lot of layers and is gonna be unique to your setup and how your local Windows installation was/is setup. For instance, admin account,  groups, Windows 10 (pre or post-11-compatibility updates) or Windows  11 version and how each handles UAC and temp. admin rights to installers, any changes made to secondary drive and how it was configured when installed, etc. etc.

I experienced a lot of issues after doing a 10  -> 11 Pro upgrade early last year and having a large Steam game library with about 1TB of game installs on a secondary SATA drive and some, including their vcruntimes on my primary SSD. The  games on the secondary lost full write access to files and folders in my User directory, thus some being unable to keep config file changes to .ini or .xml files stored there. Some broke because they relied on VCruntime DLLs on my main drive alongside Steam. To make it worse, things like Rockstar Installer/third-party DRM (which is now layered like Windows -> Steam -> Rockstar Launcher in the permission circle jerk) completely broke for some games and needed an actual dev patch in LA Noire's case.

**Comment by marticliment** [comment]
I am going to close this since this is an issue with scoop, and not with wingetui nor its scoop integration
