### ISSUE TITLE
[BUG/ISSUE] (Find the Trojan in file, or false alarm)

### ISSUE THREAD

**Issue by Devopsik404** [marticliment/WingetUI#656]
I find ` Win64/Heur.Generic.H8oAStsA` in path `C:\Users\Me\AppData\Local\Programs\WingetUI\WingetUI.exe`
Scanned by 360 total security.

![image](https://user-images.githubusercontent.com/103890449/215267875-e831900f-a93a-4728-9fb9-f15525107a05.png)

**Comment by marticliment** [comment]
please analyze the file on virus total, to see how many vendors flag wingetui as virus.


from where did you download it?

**Comment by Marcuswright1** [comment]
actually, my wingetui.exe is also being flagged by Bitdefender antivirus after the update and Bitdefender has deleted and disinfected gsudo.exe, which is affecting the program as I no longer can download or update apps. 

I have also tried completely uninstalling and reinstall but during installation process of wingetui gsudo.exe is continuously blocked by Bitdefender and won't let it extract and have to skip it which brings back the same problem of apps not installing or updating.

Really love using this application, pls help resolve this issue.

**Comment by marticliment** [comment]
I am sorry, you will need to whitelist gsudo. It is not a virus, and BitDefender is reporting it as a false positive. No other major security vendors flag gsudo.exe as a virus. Check out virustotal results (8 out of 70, none of them is a major security vendor):
https://www.virustotal.com/gui/file/1acd324cf636c53012b57467fd7a356520d4199e45acda4a0876cb52c03091a1/detection

And the same thing goes for wingetui.exe. Only 2 vendors flag it as virus:
https://www.virustotal.com/gui/file/00ddb0695da229aac7d65e9e866efe06a97bfcd7996571b646fc57b2daf291cf

**Comment by Marcuswright1** [comment]
ill attach screenshots for your reference

![Screenshot4](https://user-images.githubusercontent.com/120603862/216778009-6c069e5e-ef9f-43eb-90f9-112d79b62502.png)
![Screenshot1](https://user-images.githubusercontent.com/120603862/216778011-6fa00ce1-da08-4a10-a5ec-3cb413c2e680.png)
![Screenshot2](https://user-images.githubusercontent.com/120603862/216778012-71a22ab3-ea2f-4e8c-99e9-3cd7c2893d74.png)
![Screenshot3](https://user-images.githubusercontent.com/120603862/216778013-00062e52-5525-4066-bbda-60a73d695108.png)

**Comment by marticliment** [comment]
Those is- files are inno setup temporary files.
Where you installing something when this popped up?

**Comment by Marcuswright1** [comment]
> Those is- files are inno setup temporary files. Where you installing something when this popped up?

Yes, also after this gsudo.exe was detected by Bitdefender and disinfected, so I had to reinstall the whole Wingetui app as it stopped me from installing or updating apps

**Comment by marticliment** [comment]
Can you please tell me which program were you installing?

**Comment by Marcuswright1** [comment]
> Can you please tell me which program were you installing?

I think so MSI Kombustor

**Comment by marticliment** [comment]
What happens if you download msi kombustor and manually install it?
Does bitdefender also block the installer?

**Comment by dantman** [comment]
Bitdefender also blocked gsudo for me. WingetUI also failed to install an update for WingetUI. 

![image](https://user-images.githubusercontent.com/53399/216786203-f21469f2-f06d-4475-a7e4-9d83e2e78b90.png)

I'll re-install Winget UI later when I have time.

**Comment by marticliment** [comment]
What I think it happened is that bitdefender blocked wingetui and gsudo since the installer of that app is launched by WingetUi through GSudo, so bitdefender blocks the whole chain.

Please test the standalone installer and post here if you succeded on installing the app you wanted to install through WingetUI or not

**Comment by dantman** [comment]
> Please test the standalone installer and post here if you succeded on installing the app you wanted to install through WingetUI or not

I don't believe I was installing something at the time. IIRC what failed was an automatic update to WingetUI. But I'll try installing outstanding updates later.

**Comment by Xeevis** [comment]
Indeed BitDefender is not pleased with how WingetUI chain works, it blocks the installer, the executable, the updater and the gsudo. Takes a lot of effort to whitelist everything.
![image](https://user-images.githubusercontent.com/5835044/216814301-b1f175be-f957-4f5f-bd4b-e26872c3639d.png)


@marticliment maybe it would go a long way if gsudo wasn't bundled? Some users may even have it already installed, just check the PATH `gsudo -v` and if missing, prompt user to install it during runtime and then install with `winget install gerardog.gsudo -e`.

For some reason BitDefender is perfectly fine with this install. It may change when wingetui.exe starts using it, but that should amount to a single whitelist entry.
![image](https://user-images.githubusercontent.com/5835044/216814199-91d6a6c6-ee0e-44e5-bd15-c8c9892bd37b.png)

**Comment by marticliment** [comment]
you can manually use intalled gsudo by enabling it from the settings.

can you please tell me which gsudo version do you hav installed?

**Comment by Marcuswright1** [comment]
@marticliment Just turned off antivirus and advanced threat defense on Bitdefender while installing Wingetui and it worked perfectly fine. But just as a concern I hope Iam not compromised by doing this as it showed gsudo as malicious application earlier.

**Comment by marticliment** [comment]
you should not, gsudo is a tool that runs given commands as administrator, by showing an UAC prompt.

it is an open source tool, you can check it out at https://github.com/gerardog/gsudo

**Comment by Xeevis** [comment]
> you can manually use intalled gsudo by enabling it from the settings.
> 
> can you please tell me which gsudo version do you hav installed?

2.0.4.0 one installed by the winget manifest
https://github.com/gerardog/gsudo/releases/download/v2.0.4/gsudoSetup.msi

gsudo.exe SHA256 `806C416E30164B8EDBA466D9654A1301889D41860E84756828D9FEF278D514A3`

gsudo.exe that comes from repo ZIP gets immediately flagged. While gsudo.exe from MSI installer is perfectly fine with BitDefender. This appears to be behavioral detection, bundling gsudo is dangerous, so it's a no-no, user intentionally installing it is okay. 

> @marticliment Just turned off antivirus and advanced threat defense on Bitdefender while installing Wingetui while reinstalling and it worked perfectly fine. But just as a concern I hope Iam not compromised by doing this as it showed gsudo as malicious application earlier.

@Marcuswright1 The danger of gsudo doesn't come from gsudo itself, it's not malicious, but it can be used by malicious code. It elevates processes to administrative level. Problem is it's masked in UAC, dialog will show you that digitally signed executable gsudo is asking for permission, but it doesn't really tell you on whose behalf. Dialog for `sudo notepad` and `sudo attackcomputer.exe` will look identical.

# SOLUTION

For anyone having AV issue and is worried about the exception hell just:

1. winget install gerardog.gsudo -e
2. winget install wingetui
3. When installer is blocked on gsudo.exe, just `Skip this file (not recommended)`
4. Go to WingetUI settings > General preferences > `Use installed GSudo instead of the bundled one`
5. Restart WingetUI and everything should work.

Only problem is that Bitdefender will flag anything that includes the gsudo.exe so WingetUI installer and updater will still be quarantined when scanner gets it's hands on them. Not bundling this executable would solve this.

**Comment by marticliment** [comment]
if you download the x86 and x64 zipped versions (not the msi) from the gsudo releases page, does Bitdefender also flag them?

**Comment by Xeevis** [comment]
Yup

![image](https://user-images.githubusercontent.com/5835044/216849664-add5e5f8-55f5-4882-a517-8c94c531501a.png)

**Comment by marticliment** [comment]
then, as you can see, the issue would be with gsudo and not with the fact that it has been bundled.


could you please open an issue there?

**Comment by Xeevis** [comment]
I just did https://github.com/gerardog/gsudo/issues/232, but this is a named PUP threat, not a false positive. It's blocked by Antivirus, Advanced Threat Protection, Online Threat Prevention, basically every part of the protection suite was set to consider it a threat and if it's because of the intended behavior of the binary there's not much else that can be done.

**Comment by marticliment** [comment]
Yes, BitDefender should do something. This is a false positive, and the job of an antivirus is to both protect the user but also to allow the user to run any non-infectious virus.

What BitDefender can't do is chain-block everything that takes part in the execution of an unidentified file (which was that MSI installer, that was not even a virus after all). No other antivirus does that, and to put it on an example, bitdefender acts as a doctor who chops your entire finger for just a little scratch on the tip. I mean, it technically works, but you can't just block everything _to protect the user._ It is for this job that Windows in S/SE mode was invented

It is their job th get false positive detection fixed, since you are paying around $160/year at least to get their protection.
The file we are talikng about is not an unknown file, it is digitally signed, it has more than 24k downloads and the digital signature has a good reputation.

If you want, upvote gsudo as safe in https://www.virustotal.com/gui/file/1acd324cf636c53012b57467fd7a356520d4199e45acda4a0876cb52c03091a1/community


Please, [BitDefender](https://github.com/bitdefender), get this thing fixed.

**Comment by ppvnf** [comment]
Info about how to contact av vendors https://www.techsupportalert.com/how-to-report-malware-or-false-positives-to-multiple-antivirus-vendors/

**Comment by marticliment** [comment]
I am going to close this, since it can not be fixed from WingetUI
