### ISSUE TITLE
[BUG] (Startup)

### ISSUE THREAD

**Issue by UStress** [marticliment/WingetUI#790]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## To Reproduce
Steps to reproduce the behaviour:

## The Log

<details>

```
Please paste here the log (Go to the three dots menu on the top-right corner of WingetUI -> Winget Log. 

If the issue can be reproduced, please send the log AFTER reproducing the issue (1. Launch WingetUI, 2. Reproduce the issue, 3. Paste the log)
```

</details>

**Comment by marticliment** [comment]
This issue is being worked on. The crash will be fixed soon

**Comment by marticliment** [comment]
Hi, please delete this folder:

C:\Users\<youruser>\.wingetui\lang

The issue should then be fixed

**Comment by marticliment** [comment]
Hi, Please try it again now. It was not fixed correctly Martí Climent De: StressEnviat: dilluns, 13 de març de 2023 18:43Per a: marticliment/WingetUIA/c: Martí Climent; AssignTema: Re: [marticliment/WingetUI] [BUG] (Startup) (Issue #790) Hi, please delete this folder:C:\Users.wingetui\langThe issue should then be fixedHi, Done!No... The bug occurs again (..https://i.imgur.com/jxod8O5.pnghttps://i.imgur.com/bTR8NVm.png`                        OS: Windows                   Version: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')           OS Architecture: AMD64          APP Architecture: 64bit               APP Version: 1.62                   Program: WingetUI           Program section: UI LoadingWingetUI Log:Traceback (most recent call last):  File "init.py", line 507, in loadMainUI  File ".\mainWindow.py", line 40, in init  File ".\mainWindow.py", line 98, in loadWidgets  File ".\uiSections.py", line 2579, in initValueError: unexpected '{' in field name<class 'ValueError'>: unexpected '{' in field name`—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by UStress** [comment]
Everything is working. Thx..
