### ISSUE TITLE
[BUG] Crash on start after updated to 1.6.3

### ISSUE THREAD

**Issue by user5365476586585** [marticliment/WingetUI#819]
## Describe the bug
Crash on start after updated to 1.6.3

## To Reproduce
Start WingetUI

## The Log

<details>

```
                        OS: Windows
                   Version: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: 1.63
                   Program: WingetUI
           Program section: UI Loading

-----------------------------------------------------------------------------------------



WingetUI Log:




Traceback (most recent call last):
  File "__init__.py", line 507, in loadMainUI
  File ".\mainWindow.py", line 40, in __init__
  File ".\mainWindow.py", line 98, in loadWidgets
  File ".\uiSections.py", line 2582, in __init__

ValueError: expected '}' before end of string<class 'ValueError'>: expected '}' before end of string
```

</details>

**Comment by marticliment** [comment]
Please try deleting a folder placed on your user directory called .wingetui

**Comment by qyurila** [comment]
> Please try to delete a folder named .wingetui in your user directory.

I have the same problem (1.6.4 but with the same error message) and removing `~/.wingetui` doesn't help. Tried reinstalling via the scoop and exe file from the release page, after deleting that directory.

**Comment by marticliment** [comment]
which language is your system on?

**Comment by marticliment** [comment]
Hello,

the issue should now have been fixed.

Please delete the .wingetUI folder and install an older version of WingetUI

**Comment by marticliment** [comment]
Hello,

Please test version 1.6.5

**Comment by minbert** [comment]
This issue has been resolved by [this commit](https://github.com/marticliment/WingetUI/commit/b5887765c030bec0f6d33c07d8af89caa3e0b585#diff-720769b763e840b49f54c560ab89c1dfc4f6e6f0f813dc7587918c360e5026dc).

 If you look at the 5th line of the "lang_ko.json" file, you can see that it is closed with ']' instead of '}'. This is a problem that occurs when using versions 1.6.3 and 1.6.4 in Korean, and it has been confirmed that version 1.6.5
 
 You can close this issue.
