### ISSUE TITLE
Feature request: Add 'msstore' as a source for Winget

### ISSUE THREAD

**Issue by RavenMacDaddy** [marticliment/WingetUI#87]
![image](https://user-images.githubusercontent.com/67732686/179343453-1665b844-55fb-4608-9e02-dfe07ab7e51f.png)

Obviously this would allow to install apps from the Microsoft Store, and is available by default in Windows AFAIK; I've not made any specific configurations for that. (Windows 11)

It's possible through CLI, so go ahead and tell me if it's possible to add to the app.

**Comment by martinet101** [comment]
I tried with early winget versions and it was an absolute disaster. I'll try it again with those new stabler builds

**Comment by martinet101** [comment]
For the moment, msstore origin search does not allow full searches, so thay won't be added. (Please note that updates are managed through the MS Store and they can still be uninstalled from ElevenClock)

**Comment by upintheairsheep** [comment]
It might be possible using the API of this tool:
https://store.rg-adguard.net/

and for searching, a headless browser can be used.

**Comment by marticliment** [comment]
do they have an open api?

**Comment by upintheairsheep** [comment]
> do they have an open api?

Yes, they do have an easily reverse engineerable API, however this only gets the appx and msix files, not the search and metadata. For MSStore you could use some sort of headless browser

**Comment by marticliment** [comment]
reverse engeenering a private api is not an acceptable thing, because youwe would. be using their resources without their permission, which:
1. is not ethical
2. is unreliable and can break at any time


also, using a browser to gather information is not reliable, because we would be
1. infringing Microsoft terms
2. hidden browser Windows are resource intensive and, in general, not a good practice
3. a little change in the website would break completely the script.

winget in fact soees support Microsoft store packages, but with one particularity: winget can not lost all available packages, resulting in the impisiblity to get a list of all of them.
Thats why msstore apps are not shown.
if you find a way to get a list of all of them, please let me know and I'll add it.

**Comment by ppvnf** [comment]
what about this one?
https://github.com/ThomasPe/MS-Store-API
https://github.com/ThomasPe/MS-Store-API/blob/master/endpoints/v9.0/manifestSearch.md

**Comment by marticliment** [comment]
The issue here is the same as winget (in fact, winget uses this api): Ther's no way to get a list of all the packages.

**Comment by marticliment** [comment]
This issue has been fixed in #1042

**Comment by Alistair1231** [comment]
So this is implemented after all? I came here from the FAQ, which stated this as proof that it won't be implemented?

> Q: Can I add "msstore" as a source for Winget in the app?
A: This is not possible, nor is it planned for the near future.
See more details in issue https://github.com/marticliment/WingetUI/issues/87.

**Comment by marticliment** [comment]
yes, but I finished changing all the legacy codebase, so msstore and other dynamic load package managers could be implemented

**Comment by Alistair1231** [comment]
Ah. well awesome. I also now saw that it said "near future". 
Thanks for the response
