### ISSUE TITLE
[WINGET] Sometimes package update fails

### ISSUE THREAD

**Issue by panther7** [marticliment/WingetUI#878]
## Describe the issue   
WingetUI fail:   
  - ![2023-04-06 10 53 20](https://user-images.githubusercontent.com/3808250/230327928-39abe38b-f0eb-42f6-8877-7ec5254564e8.png)

Powershell command wingetui, ok:   
   - ![2023-04-06 10 54 24](https://user-images.githubusercontent.com/3808250/230327936-5a5ce976-278e-4fc0-a9e9-42856f40d5b0.png)

## To Reproduce
Steps to reproduce the behaviour:
1. Install old version SUbitleEdit: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEdit-3.6.11-Setup.exe
2. Run WIngetUI update

## The Log

<details>

```
🟢 Have permission to install, starting installation threads...
[]
['C:\\Users\\filip\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'upgrade', '-e', '--id', 'Nikse.SubtitleEdit', '--include-unknown', '--source', 'winget', '--accept-source-agreements', '--silent']
🟢 winget installer assistant thread started for process <Popen: returncode: None args: ['C:\\Users\\filip\\AppData\\Local\\Programs\...>
-1978335189
```

</details>

**Comment by N0rbert** [comment]
Same here. Seen this while trying to upgrade RTools and RStudio.  Also it happens when installing queue of packages.

I would recommend to control exit status of `winget` (or other backend), allow WingetUI to retry for example 3 times and only then show "fatal" error message to the user. Current behavior confuses user.

**Comment by marticliment** [comment]
hello guys, which version of winget are you running on your system?

**Comment by N0rbert** [comment]
Thanks! 
It happened with winget v1.4.10173 (aka 1.19.2301.17003 in file properties, on details tab).

**Comment by panther7** [comment]
Yes, 1.4.10173

**Comment by JAK1047** [comment]
So -1978335189 is APPINSTALLER_CLI_ERROR_UPDATE_NOT_APPLICABLE which makes sense considering the error message. I've seen this on a few other apps as well outside of Winget UI using just Winget. (EmEditor for example). In this particular case, on my system at least, following along with the testing steps for SubtitleEdit I see WinGet upgrade runs the first time and _appears_ successful since 3.6.12.0 is installed, however Winget still shows it as available for update. Looks to me like the developers didn't make it a supersedence over the previous version, so instead it just installs it side by side.

![image](https://user-images.githubusercontent.com/29665481/230827590-cb0b844b-d467-4b75-b450-4c54e56b5c98.png)

Because of this Winget still sees the 3.6.11.0 version as available for an update when checking the local index.db, but comes back as not applicable because 3.6.12.0 is technically installed.

![image](https://user-images.githubusercontent.com/29665481/230827554-048f9be7-837a-491d-afad-eb7b961d5376.png)

![image](https://user-images.githubusercontent.com/29665481/230827725-3ee234df-aad0-43c8-aee4-a0ab2459bf63.png)

Even if I just use the --all switch to bypass checking and upgrade it after the success I still see it as available thanks to the installed older version.

![image](https://user-images.githubusercontent.com/29665481/230828927-8a6e1888-5153-437b-90e2-b77313a3567b.png)

@panther7 if you install .11 normally, hit update from WingetUI, then check normal Add or Remove Programs in Windows do you also have the 2 versions installed side by side?
 

P.S. That return code gets used by Winget for any reason at all that an upgrade isn't applicable (For example if the developers swapped from a MSI to an AppX or Exe), but doesn't explain _why_ it's not applicable unless you run upgrade with the verbose logs switch and dig in. They could definitely due to improve communication to the end user there.

**Comment by marticliment** [comment]
This issue has been fixed, and the fix will be released with the next version
